### ISSUE TITLE
vpc-cni addon configuration example

### ISSUE THREAD

**Issue by ytsarev** [upbound/configuration-aws-eks#12]
### What problem are you facing?

As a follow-up to https://github.com/upbound/configuration-aws-eks/pull/11

we need to provide example of vpc-cni addon configuration, similar to

```

      - name: vpcCniAddon
        base:
          apiVersion: eks.aws.upbound.io/v1beta1
          kind: Addon
          spec:
            forProvider:
              addonName: vpc-cni
              resolveConflicts: OVERWRITE
              clusterNameSelector:
                matchControllerRef: true
              configurationValues: '{"env": {"AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG":"true", "ENI_CONFIG_LABEL_DEF":"topology.kubernetes.io/zone", "WARM_IP_TARGET":"10", "WARM_ENI_TARGET":"0", "WARM_PREFIX_TARGET": "0"}}'
```

As was pointed out by @haarchri , it should also involve the `vpc-cni` creation ordering, as addon should be created after the Cluster but before NodeGroup for proper config propagation. 

### How could Upbound help solve your problem?

Extend Configuration with the associated example
