### ISSUE TITLE
Connection secret is empty

### ISSUE THREAD

**Issue by ytsarev** [upbound/configuration-aws-eks#132]
### What happened?

```
k -n upbound-system get secret
NAME                                              TYPE                                DATA   AGE
configuration-gitops-flux-kubeconfig              connection.crossplane.io/v1alpha1   0      28m
fedfb0d2-d281-4770-85b4-8c06f11759e6-ekscluster   connection.crossplane.io/v1alpha1   3      19m
```

even when writeConnectionSecretToRef is properly defined

```
                    apiVersion: "aws.platform.upbound.io/v1alpha1"
                    kind: "XEKS"
                    metadata.name: "configuration-gitops-flux-cluster"
                    spec = {
                        parameters = {
                            accessConfig = {
                                authenticationMode = "API_AND_CONFIG_MAP"
                                bootstrapClusterCreatorAdminPermissions = True
                            }
                            id = "uptest-gitops-flux-cluster"
                            nodes = {
                                count = 1
                                instanceType = "t3.small"
                            }
                            region = "us-west-1"
                            version = "1.27"
                        }
                        writeConnectionSecretToRef = {
                            name = "configuration-gitops-flux-kubeconfig"
                            namespace = "upbound-system"
                        }
                    }
                }
```

We most probably didn't notice it because the XEKS generates correct usable ProviderConfigs for helm and kubernetes providers and in most cases we consume them directly in higher level abstractions

```
k get providerconfigs.helm.crossplane.io
NAME                                AGE
uptest-gitops-flux-cluster          31m

k get providerconfigs.kubernetes.crossplane.io
NAME                         AGE
uptest-gitops-flux-cluster   32m
```

```
k get providerconfigs.kubernetes.crossplane.io -o yaml
...
  spec:
    credentials:
      secretRef:
        key: kubeconfig
        name: fedfb0d2-d281-4770-85b4-8c06f11759e6-ekscluster <-- direct Cluster MR secret consumption
        namespace: upbound-system
      source: Secret 
```

### How can we reproduce it?

Instantiate XEKS is writeConnectionSecretToRef, observe the empty Secret

### What environment did it happen in?

Upbound
